"""
source_service.py
Deterministic backend service for Phase 9: Built-in Source Code Viewer.
Retrieves, caches, sanitizes, and analyzes single source code files on demand
with 0 LLM calls and max 1 GitHub call on cache miss.
"""

import os
import re
from typing import Dict, Any, Optional, List
from security import (
    is_binary_file,
    is_sensitive_file,
    sanitize_content,
)
from github_client import get_file_content
from cache_manager import (
    get_cached_source_file,
    set_cached_source_file,
    get_cached_file_contents,
)

# Extension to syntax highlighting language mapping
LANGUAGE_MAP: Dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "jsx",
    ".ts": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".tsx": "tsx",
    ".json": "json",
    ".json5": "json",
    ".jsonc": "json",
    ".css": "css",
    ".scss": "scss",
    ".sass": "scss",
    ".less": "less",
    ".html": "html",
    ".htm": "html",
    ".md": "markdown",
    ".markdown": "markdown",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".sql": "sql",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".cc": "cpp",
    ".xml": "xml",
    ".svg": "xml",
    ".toml": "toml",
    ".ini": "ini",
    ".env": "ini",
    ".dockerfile": "dockerfile",
    "dockerfile": "dockerfile",
}

GENERATED_FILE_PATTERNS = [
    re.compile(r"(?:^|/)(?:package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|Gemfile\.lock|poetry\.lock|composer\.lock)$", re.IGNORECASE),
    re.compile(r"\.(?:min\.js|min\.css|bundle\.js|chunk\.js|map|d\.ts\.map)$", re.IGNORECASE),
    re.compile(r"(?:^|/)(?:dist|build|out|\.next|\.nuxt)/", re.IGNORECASE),
]

GENERATED_CONTENT_PATTERNS = [
    re.compile(r"(?:^|\n)\s*(?://|#|/\*)\s*(?:auto-?generated|code generated by|do not edit|generated by)", re.IGNORECASE),
]


def detect_language(file_path: str) -> str:
    """Detect language syntax mode from file path/extension."""
    clean = file_path.strip().replace("\\", "/")
    base = os.path.basename(clean).lower()

    if base in LANGUAGE_MAP:
        return LANGUAGE_MAP[base]

    ext = os.path.splitext(clean)[1].lower()
    return LANGUAGE_MAP.get(ext, "text")


def is_generated_file(file_path: str, content: Optional[str] = None) -> bool:
    """Detect if a file is an automatically generated or minified artifact."""
    clean = file_path.strip().replace("\\", "/")
    for pattern in GENERATED_FILE_PATTERNS:
        if pattern.search(clean):
            return True

    if content:
        # Check first 500 characters
        snippet = content[:500]
        for pattern in GENERATED_CONTENT_PATTERNS:
            if pattern.search(snippet):
                return True

    return False


def get_source_file(
    owner: str,
    repo: str,
    file_path: str,
    commit_or_branch: Optional[str] = None,
    repo_model: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Retrieve single source file with caching, sanitization, and entity metadata.
    """
    # 1. Normalize and validate file path
    clean_path = file_path.strip().replace("\\", "/")
    if (not clean_path or clean_path.startswith("/") or ":" in clean_path.split("/")[0]
            or chr(0) in clean_path or ".." in clean_path.split("/")):
        return {
            "success": False,
            "error": "Invalid file path provided.",
        }

    branch_ref = (commit_or_branch or "").strip() or None

    # 2. Binary file check
    if is_binary_file(clean_path):
        return {
            "success": True,
            "file": {
                "path": clean_path,
                "language": "binary",
                "content": None,
                "line_count": 0,
                "size": 0,
                "commit_sha": branch_ref or "default",
                "redacted": False,
                "is_sensitive": False,
                "is_binary": True,
                "is_generated": False,
                "warning": "Binary file: preview not available.",
            },
            "symbols": [],
            "routes": [],
            "models": [],
        }

    # 3. Sensitive file check (.env, credentials, etc.)
    if is_sensitive_file(clean_path):
        redacted_content = "# Sensitive value redacted\n[REDACTED SECRET FILE]\n"
        return {
            "success": True,
            "file": {
                "path": clean_path,
                "language": "ini",
                "content": redacted_content,
                "line_count": len(redacted_content.splitlines()),
                "size": len(redacted_content),
                "commit_sha": branch_ref or "default",
                "redacted": True,
                "is_sensitive": True,
                "is_binary": False,
                "is_generated": False,
                "warning": "Sensitive value redacted",
            },
            "symbols": [],
            "routes": [],
            "models": [],
        }

    # 4. Check single-file source cache
    cached_file = get_cached_source_file(owner, repo, branch_ref or "default", clean_path)
    if cached_file:
        file_payload = cached_file
    else:
        # 5. Check if already present in bulk file_contents_cache
        cached_contents = get_cached_file_contents(owner, repo) or {}
        raw_content = cached_contents.get(clean_path)

        # 6. Fetch from GitHub if not in any cache
        if raw_content is None:
            try:
                raw_content = get_file_content(owner, repo, clean_path, branch=branch_ref)
            except Exception as e:
                return {
                    "success": False,
                    "error": f"Failed to retrieve file from GitHub: {str(e)}",
                }

        # 7. Sanitize content and detect secrets
        sanitized = sanitize_content(clean_path, raw_content)
        if sanitized is None:
            sanitized = "# Sensitive value redacted\n"
            was_redacted = True
        else:
            was_redacted = "[REDACTED SECRET]" in sanitized
            if was_redacted:
                sanitized = sanitized.replace("[REDACTED SECRET]", "[Sensitive value redacted]")

        # 8. Detect if generated
        is_gen = is_generated_file(clean_path, sanitized)
        line_count = len(sanitized.splitlines()) if sanitized else 0

        warning = "Generated file" if is_gen else None
        if line_count > 5000:
            warning = f"{warning}; large file ({line_count} lines)" if warning else f"Large file ({line_count} lines)"

        file_payload = {
            "path": clean_path,
            "language": detect_language(clean_path),
            "content": sanitized,
            "line_count": line_count,
            "size": len(sanitized.encode("utf-8")),
            "commit_sha": branch_ref or "default",
            "redacted": was_redacted,
            "is_sensitive": False,
            "is_binary": False,
            "is_generated": is_gen,
            "warning": warning,
        }

        # Cache in thread-safe TTL cache
        set_cached_source_file(owner, repo, branch_ref or "default", clean_path, file_payload)

    # 9. Extract symbols, routes, and models from RepositoryModel without re-parsing
    file_symbols: List[Dict[str, Any]] = []
    file_routes: List[Dict[str, Any]] = []
    file_models: List[Dict[str, Any]] = []

    if repo_model:
        # Symbols in this file
        raw_symbols = repo_model.get("symbols", []) or []
        for s in raw_symbols:
            if s.get("file") == clean_path:
                file_symbols.append(s)

        # If empty, check file model's functions/classes
        if not file_symbols:
            file_meta = (repo_model.get("files") or {}).get(clean_path)
            if isinstance(file_meta, dict):
                for fn in file_meta.get("functions") or []:
                    fn_name = fn if isinstance(fn, str) else fn.get("name")
                    if fn_name:
                        file_symbols.append({"name": fn_name, "file": clean_path, "type": "function"})
                for cls in file_meta.get("classes") or []:
                    cls_name = cls if isinstance(cls, str) else cls.get("name")
                    if cls_name:
                        file_symbols.append({"name": cls_name, "file": clean_path, "type": "class"})

        # API routes in this file
        raw_routes = repo_model.get("api_routes", []) or []
        for r in raw_routes:
            if r.get("file") == clean_path:
                file_routes.append(r)

        # Database models in this file
        raw_models = repo_model.get("database_models", []) or []
        for m in raw_models:
            if m.get("file") == clean_path:
                file_models.append(m)

    return {
        "success": True,
        "file": file_payload,
        "symbols": file_symbols,
        "routes": file_routes,
        "models": file_models,
    }
