"""
test_source_service.py
Unit tests for Phase 9 Built-in Source Code Viewer backend service and API endpoint.
Deterministic in-memory fixtures. No live GitHub or LLM calls.
"""

import unittest
from source_service import (
    detect_language,
    is_generated_file,
    get_source_file,
)
from cache_manager import (
    clear_cache,
    set_cached_source_file,
    set_cached_file_contents,
    set_cached_repository_model,
)
from web_app import app


class TestSourceService(unittest.TestCase):

    def setUp(self):
        clear_cache()
        self.mock_model = {
            "symbols": [
                {"name": "login", "file": "src/services/auth.ts", "type": "function", "line": 15},
                {"name": "AuthService", "file": "src/services/auth.ts", "type": "class", "line": 5},
            ],
            "api_routes": [
                {"method": "POST", "path": "/api/login", "file": "src/services/auth.ts", "handler": "login"}
            ],
            "database_models": [
                {"name": "User", "file": "src/models/User.ts", "framework": "TypeORM"}
            ],
        }

    def test_language_detection(self):
        """File extensions should map deterministically to syntax modes."""
        self.assertEqual(detect_language("script.py"), "python")
        self.assertEqual(detect_language("src/App.tsx"), "tsx")
        self.assertEqual(detect_language("src/index.ts"), "typescript")
        self.assertEqual(detect_language("package.json"), "json")
        self.assertEqual(detect_language("README.md"), "markdown")
        self.assertEqual(detect_language("deploy.sh"), "shell")
        self.assertEqual(detect_language("query.sql"), "sql")
        self.assertEqual(detect_language("styles.css"), "css")
        self.assertEqual(detect_language("unknown.xyz"), "text")

    def test_generated_file_detection(self):
        """Recognize generated and minified files by name and content."""
        self.assertTrue(is_generated_file("package-lock.json"))
        self.assertTrue(is_generated_file("bundle.min.js"))
        self.assertTrue(is_generated_file("dist/app.js"))
        self.assertTrue(is_generated_file("file.ts", "// Code generated by protoc. DO NOT EDIT."))
        self.assertFalse(is_generated_file("src/services/auth.ts", "export const login = () => {}"))

    def test_binary_file_handling(self):
        """Binary files must return metadata with content=None and is_binary=True."""
        res = get_source_file("owner", "repo", "weights.keras")
        self.assertTrue(res["success"])
        file_info = res["file"]
        self.assertTrue(file_info["is_binary"])
        self.assertIsNone(file_info["content"])
        self.assertIn("preview not available", file_info["warning"].lower())

    def test_sensitive_file_handling(self):
        """Sensitive files (.env, id_rsa) must have content redacted."""
        res = get_source_file("owner", "repo", ".env")
        self.assertTrue(res["success"])
        file_info = res["file"]
        self.assertTrue(file_info["redacted"])
        self.assertIn("Sensitive value redacted", file_info["content"])

    def test_secret_sanitization_in_content(self):
        """Secrets appearing in normal files must be sanitized to [Sensitive value redacted]."""
        raw_code = 'const apiKey = "sk-proj-1234567890123456789012345678901234567890";\nconsole.log(apiKey);'
        set_cached_file_contents("owner", "repo", {"src/config.ts": raw_code})

        res = get_source_file("owner", "repo", "src/config.ts")
        self.assertTrue(res["success"])
        file_info = res["file"]
        self.assertTrue(file_info["redacted"])
        self.assertIn("[Sensitive value redacted]", file_info["content"])
        self.assertNotIn("sk-proj-", file_info["content"])

    def test_source_cache_hit(self):
        """Second call should retrieve from cache without any external lookups."""
        cached_payload = {
            "path": "src/utils.ts",
            "language": "typescript",
            "content": "export const add = (a, b) => a + b;",
            "line_count": 1,
            "size": 36,
            "commit_sha": "main",
            "redacted": False,
            "is_binary": False,
            "is_generated": False,
            "warning": None,
        }
        set_cached_source_file("owner", "repo", "main", "src/utils.ts", cached_payload)

        res = get_source_file("owner", "repo", "src/utils.ts", commit_or_branch="main")
        self.assertTrue(res["success"])
        self.assertEqual(res["file"]["content"], cached_payload["content"])

    def test_commit_aware_cache(self):
        """Different commits must maintain separate cache entries."""
        payload_v1 = {"path": "file.ts", "content": "v1"}
        payload_v2 = {"path": "file.ts", "content": "v2"}

        set_cached_source_file("owner", "repo", "sha-1", "file.ts", payload_v1)
        set_cached_source_file("owner", "repo", "sha-2", "file.ts", payload_v2)

        res1 = get_source_file("owner", "repo", "file.ts", commit_or_branch="sha-1")
        res2 = get_source_file("owner", "repo", "file.ts", commit_or_branch="sha-2")

        self.assertEqual(res1["file"]["content"], "v1")
        self.assertEqual(res2["file"]["content"], "v2")

    def test_invalid_path_traversal(self):
        """Directory traversal attempts must be rejected."""
        res = get_source_file("owner", "repo", "../secret.txt")
        self.assertFalse(res["success"])
        self.assertIn("Invalid file path", res["error"])

    def test_metadata_extraction_from_repo_model(self):
        """Symbols and routes from repository model must be attached without re-parsing."""
        raw_code = "export class AuthService {}\nexport function login() {}\n"
        set_cached_file_contents("owner", "repo", {"src/services/auth.ts": raw_code})

        res = get_source_file("owner", "repo", "src/services/auth.ts", repo_model=self.mock_model)
        self.assertTrue(res["success"])
        self.assertEqual(len(res["symbols"]), 2)
        self.assertEqual(res["symbols"][0]["name"], "login")
        self.assertEqual(len(res["routes"]), 1)
        self.assertEqual(res["routes"][0]["path"], "/api/login")

    def test_api_source_endpoint(self):
        """Flask endpoint /api/source must respond with 200 on GET and POST."""
        client = app.test_client()

        # Missing params -> 400
        resp_bad = client.get("/api/source")
        self.assertEqual(resp_bad.status_code, 400)

        # Valid cached file via POST
        set_cached_repository_model("testowner", "testrepo", self.mock_model)
        set_cached_file_contents("testowner", "testrepo", {"src/services/auth.ts": "const x = 1;"})

        resp_post = client.post(
            "/api/source",
            json={
                "url": "https://github.com/testowner/testrepo",
                "path": "src/services/auth.ts",
            },
        )
        self.assertEqual(resp_post.status_code, 200)
        json_data = resp_post.get_json()
        self.assertTrue(json_data["success"])
        self.assertEqual(json_data["file"]["content"], "const x = 1;")
        self.assertEqual(json_data["file"]["language"], "typescript")

        # Valid cached file via GET
        resp_get = client.get("/api/source?url=https://github.com/testowner/testrepo&path=src/services/auth.ts")
        self.assertEqual(resp_get.status_code, 200)
        self.assertTrue(resp_get.get_json()["success"])


if __name__ == "__main__":
    unittest.main()
